MODEL:
  NUM_CLASSES: 81
  BOX_HEAD:
    PREDICTOR: 'SSDLiteBoxPredictor'
  BACKBONE:
    NAME: 'mobilenext'
    OUT_CHANNELS: (576, 1280, 512, 256, 256, 128)
  PRIORS:
    FEATURE_MAPS: [20, 10, 5, 3, 2, 1]
    STRIDES: [16, 32, 64, 120, 160, 320]
    MIN_SIZES: [45, 90, 135, 180, 225, 270]
    MAX_SIZES: [90, 135, 180, 225, 270, 315]
    ASPECT_RATIOS: [[2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2]]
    BOXES_PER_LOCATION: [6, 6, 6, 6, 6, 4]
INPUT:
  IMAGE_SIZE: 320
DATASETS:
  TRAIN: ("coco_2017_train", ) # "coco_2014_valminusminival")
  TEST: ("coco_2017_val", )
SOLVER:
  MAX_ITER: 1600000
  LR_STEPS: [280000, 360000]
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-2
  WEIGHT_DECAY: 4e-5
TEST:
  CONFIDENCE_THRESHOLD: 0.05
  NMS_THRESHOLD: 0.5

OUTPUT_DIR: 'outputs/mobilenext_coco_ssdlite_2'
