MODEL:
  NUM_CLASSES: 81
  BOX_HEAD:
    PREDICTOR: 'SSDLiteBoxPredictor'
  BACKBONE:
    NAME: 'mobilenext'
    OUT_CHANNELS: (128, 128, 128, 128, 128)
  PRIORS:
    FEATURE_MAPS: [40, 20, 10, 5, 3]
    STRIDES: [8, 16, 32, 64, 128]
    MIN_SIZES: [45, 90, 135, 180, 270]
    MAX_SIZES: [90, 135, 180, 270, 315]
    ASPECT_RATIOS: [[2, 3], [2, 3], [2, 3], [2, 3], [2, 3]]
    BOXES_PER_LOCATION: [6, 6, 6, 6, 6]
INPUT:
  IMAGE_SIZE: 320
DATASETS:
  TRAIN: ("coco_2017_train", ) # "coco_2014_valminusminival")
  TEST: ("coco_2017_val", )
SOLVER:
  MAX_ITER: 1600000
  LR_STEPS: [280000, 360000]
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-2
  WEIGHT_DECAY: 4e-5
TEST:
  CONFIDENCE_THRESHOLD: 0.05
  NMS_THRESHOLD: 0.5

OUTPUT_DIR: 'outputs/mnext_fpn_coco'
