MODEL:
  NUM_CLASSES: 80
  BOX_HEAD:
    PREDICTOR: 'SSDLiteBoxPredictor'
  BACKBONE:
    NAME: 'se_mbv2'
    OUT_CHANNELS: (96, 1280, 512, 256, 256, 64)
    # OUT_CHANNELS: (128, 128, 128, 128, 128)
  PRIORS:
    FEATURE_MAPS: [20, 10, 5, 3, 2, 1]
    STRIDES: [16, 32, 64, 120, 160, 320]
    MIN_SIZES: [45, 90, 135, 180, 225, 270]
    MAX_SIZES: [90, 135, 180, 225, 270, 315]
    #MIN_SIZES: [32, 45, 90, 135, 180, 270]
    #MAX_SIZES: [90, 135, 180, 225, 270, 325]
    # STRIDES: [16, 32, 64, 120, 160, 320]
    ASPECT_RATIOS: [[2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2]]
    BOXES_PER_LOCATION: [6, 6, 6, 6, 6, 4]
    # FEATURE_MAPS: [40, 20, 10, 5, 3]
    # STRIDES: [8, 16, 32, 64, 128]
    # MIN_SIZES: [45, 90, 135, 180, 270]
    # MAX_SIZES: [90, 135, 180, 270, 315]
    # #MIN_SIZES: [32, 45, 90, 135, 180, 270]
    # #MAX_SIZES: [90, 135, 180, 225, 270, 325]
    # # STRIDES: [16, 32, 64, 120, 160, 320]
    # ASPECT_RATIOS: [[2, 3], [2, 3], [2, 3], [2, 3], [2, 3]]
    # BOXES_PER_LOCATION: [6, 6, 6, 6, 6]
INPUT:
  IMAGE_SIZE: 320
DATASETS:
  TRAIN: ("coco_2017_train", ) # "coco_2014_valminusminival")
  TEST: ("coco_2017_val", )
SOLVER:
  MAX_ITER: 1600000
  LR_STEPS: [1120000, 1440000]
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-2
  WEIGHT_DECAY: 4e-5
TEST:
  CONFIDENCE_THRESHOLD: 0.05
  NMS_THRESHOLD: 0.5

OUTPUT_DIR: 'outputs/se_mbv2_ssd320_coco'
